#!/usr/bin/env bash

# Set up aliases for the common commands
alias node="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts node"
alias npm="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts npm"
alias yarn="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts yarn"