#!/usr/bin/env bash

# Set up aliases for the common commands
alias dnode="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts node"
alias dnpm="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts npm"
alias dyarn="docker run --rm -it --name node -v \$PWD:/app -w /app node:lts yarn"
